# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and test SDK

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
        AAD_APP_CLIENT_ID: ${{ secrets.AAD_APP_CLIENT_ID }}
        AAD_APP_CLIENT_SECRET: ${{ secrets.AAD_APP_CLIENT_SECRET }}
        AAD_APP_CERT: ${{ secrets.AAD_APP_CERT }}
        AAD_APP_CERT_SECRET: ${{ secrets.AAD_APP_CERT_SECRET }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        SHA: ${{ github.sha }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build JAR, Sources, and Docs with Maven
      run: mvn -B package --file sdk/pom.xml -Dsha=${SHA:0:7}
    - name: Copy artifacts to single directory
      run: chmod +x ./prepareOutput.sh && ./prepareOutput.sh $(echo ${SHA:0:7})
